# Generated by Django 5.0 on 2024-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=38.5403, max_digits=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=68.4589, max_digits=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
